image: 
   file: .gitpod.Dockerfile


# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: first
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  
  - name: second
    init: dapr init
    command: export PATH=$PATH:/home/gitpod/.dapr/bin
  - name: third
    command: docker-compose up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
